global:
  experiment: 99999
  blast_db_name: core_nt.20240803
  blast_db_path: resources/core_nt
  stat_dbss: resources/tree_filter.20240830.dbss
  stat_index: 'resources/tree_index.20240830.dbs'
  stat_annotation: 'resources/tree_filter.20240830.dbss.annotation'
  human_virus_taxlist: 'resources/human_viruses_taxlist.txt'
  out_dir: output
  gettax_sqlite_path: resources/gettax.sqlite
samples:
- name: Illumina_test
  r1_fastq: data/illumina.R1.fq.gz
  r2_fastq: data/illumina.R2.fq.gz
- name: ONT_test
  ont: data/ont.fq.gz
# - name: AE0000100A9532
#   sra: SRR24010792