global:
  experiment: 30594
  blast_db_name: core_nt.20240803
  blast_db_path: resources/core_nt
  stat_dbss: resources/tree_filter.20240830.dbss
  stat_index: 'resources/tree_index.20240830.dbs'
  stat_annotation: 'resources/tree_filter.20240830.dbss.annotation'
  human_virus_taxlist: 'resources/human_viruses_taxlist.txt'
  out_dir: /staging/groups/oconnor_group/30594/output
  gettax_sqlite_path: resources/gettax.sqlite
  labkey_server: 
  labkey_project_name:
  labkey_api_key: 
  labkey_username: 
  labkey_password: 
  webdav_url: 
